SELECT * FROM ADMGTIN14VariableLogistica VLGTIN14 WHERE VLGTIN14.IdInterno  = 1003  ORDER BY VLGTIN14.ConsecutivoGTIN14 ASC --VER ACEITE
SELECT * FROM ADMGTIN14VariableLogistica VLGTIN14 WHERE VLGTIN14.IdInterno  = 1002  ORDER BY VLGTIN14.ConsecutivoGTIN14 ASC --VER HARINA
SELECT * FROM ADMUnidadAlistoDefecto VL WHERE VL.idArticulo IN(4, 49)