//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Diverscan.MJP.UI.ServiceMH {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OrdenCompraParametros", Namespace="http://schemas.datacontract.org/2004/07/WCFOrdenCompraCRLib")]
    [System.SerializableAttribute()]
    public partial class OrdenCompraParametros : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ClaveField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdInstitucionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int OrdenIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UsuarioField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Clave {
            get {
                return this.ClaveField;
            }
            set {
                if ((object.ReferenceEquals(this.ClaveField, value) != true)) {
                    this.ClaveField = value;
                    this.RaisePropertyChanged("Clave");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IdInstitucion {
            get {
                return this.IdInstitucionField;
            }
            set {
                if ((object.ReferenceEquals(this.IdInstitucionField, value) != true)) {
                    this.IdInstitucionField = value;
                    this.RaisePropertyChanged("IdInstitucion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int OrdenId {
            get {
                return this.OrdenIdField;
            }
            set {
                if ((this.OrdenIdField.Equals(value) != true)) {
                    this.OrdenIdField = value;
                    this.RaisePropertyChanged("OrdenId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Usuario {
            get {
                return this.UsuarioField;
            }
            set {
                if ((object.ReferenceEquals(this.UsuarioField, value) != true)) {
                    this.UsuarioField = value;
                    this.RaisePropertyChanged("Usuario");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OrdenCompraMJP", Namespace="http://schemas.datacontract.org/2004/07/GeneradorOrdenCompraMJP")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Diverscan.MJP.UI.ServiceMH.OrdenCompra))]
    public partial class OrdenCompraMJP : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FechaNotificacionOrdenCompraField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string InstitucionFechaPedidoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string InstitucionNombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string InstitucionNumeroPedidoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string InstitucionNumeroTramiteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string InstitucionPersonaContactoTelefonoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string InstitucionSociedadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string InstitucionTipoCambioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MontoTotalOrdenCompraField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Diverscan.MJP.UI.ServiceMH.OrdenCompraDetalle[] OrdenCompraDetalleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProveedorCedulaJuridicaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProveedorNombreField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FechaNotificacionOrdenCompra {
            get {
                return this.FechaNotificacionOrdenCompraField;
            }
            set {
                if ((object.ReferenceEquals(this.FechaNotificacionOrdenCompraField, value) != true)) {
                    this.FechaNotificacionOrdenCompraField = value;
                    this.RaisePropertyChanged("FechaNotificacionOrdenCompra");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string InstitucionFechaPedido {
            get {
                return this.InstitucionFechaPedidoField;
            }
            set {
                if ((object.ReferenceEquals(this.InstitucionFechaPedidoField, value) != true)) {
                    this.InstitucionFechaPedidoField = value;
                    this.RaisePropertyChanged("InstitucionFechaPedido");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string InstitucionNombre {
            get {
                return this.InstitucionNombreField;
            }
            set {
                if ((object.ReferenceEquals(this.InstitucionNombreField, value) != true)) {
                    this.InstitucionNombreField = value;
                    this.RaisePropertyChanged("InstitucionNombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string InstitucionNumeroPedido {
            get {
                return this.InstitucionNumeroPedidoField;
            }
            set {
                if ((object.ReferenceEquals(this.InstitucionNumeroPedidoField, value) != true)) {
                    this.InstitucionNumeroPedidoField = value;
                    this.RaisePropertyChanged("InstitucionNumeroPedido");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string InstitucionNumeroTramite {
            get {
                return this.InstitucionNumeroTramiteField;
            }
            set {
                if ((object.ReferenceEquals(this.InstitucionNumeroTramiteField, value) != true)) {
                    this.InstitucionNumeroTramiteField = value;
                    this.RaisePropertyChanged("InstitucionNumeroTramite");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string InstitucionPersonaContactoTelefono {
            get {
                return this.InstitucionPersonaContactoTelefonoField;
            }
            set {
                if ((object.ReferenceEquals(this.InstitucionPersonaContactoTelefonoField, value) != true)) {
                    this.InstitucionPersonaContactoTelefonoField = value;
                    this.RaisePropertyChanged("InstitucionPersonaContactoTelefono");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string InstitucionSociedad {
            get {
                return this.InstitucionSociedadField;
            }
            set {
                if ((object.ReferenceEquals(this.InstitucionSociedadField, value) != true)) {
                    this.InstitucionSociedadField = value;
                    this.RaisePropertyChanged("InstitucionSociedad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string InstitucionTipoCambio {
            get {
                return this.InstitucionTipoCambioField;
            }
            set {
                if ((object.ReferenceEquals(this.InstitucionTipoCambioField, value) != true)) {
                    this.InstitucionTipoCambioField = value;
                    this.RaisePropertyChanged("InstitucionTipoCambio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MontoTotalOrdenCompra {
            get {
                return this.MontoTotalOrdenCompraField;
            }
            set {
                if ((object.ReferenceEquals(this.MontoTotalOrdenCompraField, value) != true)) {
                    this.MontoTotalOrdenCompraField = value;
                    this.RaisePropertyChanged("MontoTotalOrdenCompra");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Diverscan.MJP.UI.ServiceMH.OrdenCompraDetalle[] OrdenCompraDetalle {
            get {
                return this.OrdenCompraDetalleField;
            }
            set {
                if ((object.ReferenceEquals(this.OrdenCompraDetalleField, value) != true)) {
                    this.OrdenCompraDetalleField = value;
                    this.RaisePropertyChanged("OrdenCompraDetalle");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProveedorCedulaJuridica {
            get {
                return this.ProveedorCedulaJuridicaField;
            }
            set {
                if ((object.ReferenceEquals(this.ProveedorCedulaJuridicaField, value) != true)) {
                    this.ProveedorCedulaJuridicaField = value;
                    this.RaisePropertyChanged("ProveedorCedulaJuridica");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProveedorNombre {
            get {
                return this.ProveedorNombreField;
            }
            set {
                if ((object.ReferenceEquals(this.ProveedorNombreField, value) != true)) {
                    this.ProveedorNombreField = value;
                    this.RaisePropertyChanged("ProveedorNombre");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OrdenCompra", Namespace="http://schemas.datacontract.org/2004/07/WCFOrdenCompraCRLib")]
    [System.SerializableAttribute()]
    public partial class OrdenCompra : Diverscan.MJP.UI.ServiceMH.OrdenCompraMJP {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Diverscan.MJP.UI.ServiceMH.Resultado ResultadoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Diverscan.MJP.UI.ServiceMH.Resultado Resultado {
            get {
                return this.ResultadoField;
            }
            set {
                if ((object.ReferenceEquals(this.ResultadoField, value) != true)) {
                    this.ResultadoField = value;
                    this.RaisePropertyChanged("Resultado");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OrdenCompraDetalle", Namespace="http://schemas.datacontract.org/2004/07/GeneradorOrdenCompraMJP")]
    [System.SerializableAttribute()]
    public partial class OrdenCompraDetalle : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CantidadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CentroGestorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodigoMercanciaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescripcionCortaMercanciaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescripcionLargaMercanciaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MonedaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MontoLineaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MontoSolicitudPedidoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NumeroLineaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NumeroSolicitudPedidoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PosicionPresupuestariaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PrecioUnitarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Diverscan.MJP.UI.ServiceMH.TextosExtras[] TextosExtrasField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UnidadMedidaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Cantidad {
            get {
                return this.CantidadField;
            }
            set {
                if ((object.ReferenceEquals(this.CantidadField, value) != true)) {
                    this.CantidadField = value;
                    this.RaisePropertyChanged("Cantidad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CentroGestor {
            get {
                return this.CentroGestorField;
            }
            set {
                if ((object.ReferenceEquals(this.CentroGestorField, value) != true)) {
                    this.CentroGestorField = value;
                    this.RaisePropertyChanged("CentroGestor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodigoMercancia {
            get {
                return this.CodigoMercanciaField;
            }
            set {
                if ((object.ReferenceEquals(this.CodigoMercanciaField, value) != true)) {
                    this.CodigoMercanciaField = value;
                    this.RaisePropertyChanged("CodigoMercancia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DescripcionCortaMercancia {
            get {
                return this.DescripcionCortaMercanciaField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripcionCortaMercanciaField, value) != true)) {
                    this.DescripcionCortaMercanciaField = value;
                    this.RaisePropertyChanged("DescripcionCortaMercancia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DescripcionLargaMercancia {
            get {
                return this.DescripcionLargaMercanciaField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripcionLargaMercanciaField, value) != true)) {
                    this.DescripcionLargaMercanciaField = value;
                    this.RaisePropertyChanged("DescripcionLargaMercancia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Moneda {
            get {
                return this.MonedaField;
            }
            set {
                if ((object.ReferenceEquals(this.MonedaField, value) != true)) {
                    this.MonedaField = value;
                    this.RaisePropertyChanged("Moneda");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MontoLinea {
            get {
                return this.MontoLineaField;
            }
            set {
                if ((object.ReferenceEquals(this.MontoLineaField, value) != true)) {
                    this.MontoLineaField = value;
                    this.RaisePropertyChanged("MontoLinea");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MontoSolicitudPedido {
            get {
                return this.MontoSolicitudPedidoField;
            }
            set {
                if ((object.ReferenceEquals(this.MontoSolicitudPedidoField, value) != true)) {
                    this.MontoSolicitudPedidoField = value;
                    this.RaisePropertyChanged("MontoSolicitudPedido");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NumeroLinea {
            get {
                return this.NumeroLineaField;
            }
            set {
                if ((object.ReferenceEquals(this.NumeroLineaField, value) != true)) {
                    this.NumeroLineaField = value;
                    this.RaisePropertyChanged("NumeroLinea");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NumeroSolicitudPedido {
            get {
                return this.NumeroSolicitudPedidoField;
            }
            set {
                if ((object.ReferenceEquals(this.NumeroSolicitudPedidoField, value) != true)) {
                    this.NumeroSolicitudPedidoField = value;
                    this.RaisePropertyChanged("NumeroSolicitudPedido");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PosicionPresupuestaria {
            get {
                return this.PosicionPresupuestariaField;
            }
            set {
                if ((object.ReferenceEquals(this.PosicionPresupuestariaField, value) != true)) {
                    this.PosicionPresupuestariaField = value;
                    this.RaisePropertyChanged("PosicionPresupuestaria");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PrecioUnitario {
            get {
                return this.PrecioUnitarioField;
            }
            set {
                if ((object.ReferenceEquals(this.PrecioUnitarioField, value) != true)) {
                    this.PrecioUnitarioField = value;
                    this.RaisePropertyChanged("PrecioUnitario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Diverscan.MJP.UI.ServiceMH.TextosExtras[] TextosExtras {
            get {
                return this.TextosExtrasField;
            }
            set {
                if ((object.ReferenceEquals(this.TextosExtrasField, value) != true)) {
                    this.TextosExtrasField = value;
                    this.RaisePropertyChanged("TextosExtras");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UnidadMedida {
            get {
                return this.UnidadMedidaField;
            }
            set {
                if ((object.ReferenceEquals(this.UnidadMedidaField, value) != true)) {
                    this.UnidadMedidaField = value;
                    this.RaisePropertyChanged("UnidadMedida");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Resultado", Namespace="http://schemas.datacontract.org/2004/07/WCFOrdenCompraCRLib")]
    [System.SerializableAttribute()]
    public partial class Resultado : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CodigoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MensajeErrorField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Codigo {
            get {
                return this.CodigoField;
            }
            set {
                if ((this.CodigoField.Equals(value) != true)) {
                    this.CodigoField = value;
                    this.RaisePropertyChanged("Codigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MensajeError {
            get {
                return this.MensajeErrorField;
            }
            set {
                if ((object.ReferenceEquals(this.MensajeErrorField, value) != true)) {
                    this.MensajeErrorField = value;
                    this.RaisePropertyChanged("MensajeError");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TextosExtras", Namespace="http://schemas.datacontract.org/2004/07/GeneradorOrdenCompraMJP")]
    [System.SerializableAttribute()]
    public partial class TextosExtras : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreCampoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ValorCampoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NombreCampo {
            get {
                return this.NombreCampoField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreCampoField, value) != true)) {
                    this.NombreCampoField = value;
                    this.RaisePropertyChanged("NombreCampo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ValorCampo {
            get {
                return this.ValorCampoField;
            }
            set {
                if ((object.ReferenceEquals(this.ValorCampoField, value) != true)) {
                    this.ValorCampoField = value;
                    this.RaisePropertyChanged("ValorCampo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceMH.IWCFOCCR")]
    public interface IWCFOCCR {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFOCCR/ObtenerOrdenCompraParams", ReplyAction="http://tempuri.org/IWCFOCCR/ObtenerOrdenCompraParamsResponse")]
        Diverscan.MJP.UI.ServiceMH.OrdenCompra ObtenerOrdenCompraParams(Diverscan.MJP.UI.ServiceMH.OrdenCompraParametros OCParams);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFOCCR/ObtenerOrdenCompra", ReplyAction="http://tempuri.org/IWCFOCCR/ObtenerOrdenCompraResponse")]
        Diverscan.MJP.UI.ServiceMH.OrdenCompra ObtenerOrdenCompra(int ordenId, string idInstitucion, string usuario, string clave);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFOCCR/VerificarUsuarioAutenticado", ReplyAction="http://tempuri.org/IWCFOCCR/VerificarUsuarioAutenticadoResponse")]
        bool VerificarUsuarioAutenticado(string usuario, string clave);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IWCFOCCRChannel : Diverscan.MJP.UI.ServiceMH.IWCFOCCR, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WCFOCCRClient : System.ServiceModel.ClientBase<Diverscan.MJP.UI.ServiceMH.IWCFOCCR>, Diverscan.MJP.UI.ServiceMH.IWCFOCCR {
        
        public WCFOCCRClient() {
        }
        
        public WCFOCCRClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WCFOCCRClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WCFOCCRClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WCFOCCRClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Diverscan.MJP.UI.ServiceMH.OrdenCompra ObtenerOrdenCompraParams(Diverscan.MJP.UI.ServiceMH.OrdenCompraParametros OCParams) {
            return base.Channel.ObtenerOrdenCompraParams(OCParams);
        }
        
        public Diverscan.MJP.UI.ServiceMH.OrdenCompra ObtenerOrdenCompra(int ordenId, string idInstitucion, string usuario, string clave) {
            return base.Channel.ObtenerOrdenCompra(ordenId, idInstitucion, usuario, clave);
        }
        
        public bool VerificarUsuarioAutenticado(string usuario, string clave) {
            return base.Channel.VerificarUsuarioAutenticado(usuario, clave);
        }
    }
}
