using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Telerik.Web.UI;
using System.Web;
using System.Web.UI;
using System.Web.UI.WebControls;
using System.Web.Compilation;

namespace Diverscan.MJP.Utilidades.general
{
    public class RadGridProperties
    {
        public void FormatearColumnas(RadGrid grid)
        {
            try
            {
                // Las instrucciones que están dentro de los IF lo que hacen es solamente ponerle la 
                // primera letra en mayúscula, con esto le damos más estandar a los nombres de las columnas
                foreach (GridColumn col in grid.MasterTableView.AutoGeneratedColumns)
                {
                    if (col.UniqueName.StartsWith("txtid"))
                    {
                        col.HeaderText = char.ToUpper(col.UniqueName.Replace("txtid", "")[0]) + col.UniqueName.Replace("txtid", "").Substring(1);
                    }
                    else if (col.UniqueName.StartsWith("txt id"))
                    {
                        col.HeaderText = char.ToUpper(col.UniqueName.Replace("txt id", "")[0]) + col.UniqueName.Replace("txt id", "").Substring(1);
                    }
                    else if (col.UniqueName.StartsWith("txt"))
                    {
                        col.HeaderText = char.ToUpper(col.UniqueName.Replace("txt", "")[0]) + col.UniqueName.Replace("txt", "").Substring(1);
                    }
                    else if (col.UniqueName.StartsWith("txm"))
                    {
                        col.HeaderText = char.ToUpper(col.UniqueName.Replace("txm", "")[0]) + col.UniqueName.Replace("txm", "").Substring(1);
                    }
                    else if (col.UniqueName.StartsWith("ddlid"))
                    {
                        col.HeaderText = char.ToUpper(col.UniqueName.Replace("ddlid", "")[0]) + col.UniqueName.Replace("ddlid", "").Substring(1);
                    }
                    else if (col.UniqueName.ToLower().StartsWith("ddl id"))
                    {
                        col.HeaderText = char.ToUpper(col.UniqueName.ToLower().Replace("ddl id", "")[0]) + col.UniqueName.ToLower().Replace("ddl id", "").Substring(1);
                    }
                    else if (col.UniqueName.ToLower().StartsWith("txtlid"))
                    {
                        col.HeaderText = char.ToUpper(col.UniqueName.ToLower().Replace("txtlid", "")[0]) + col.UniqueName.ToLower().Replace("txtlid", "").Substring(1);
                    }
                    else if (col.UniqueName.ToLower().StartsWith("chk"))
                    {
                        col.HeaderText = char.ToUpper(col.UniqueName.ToLower().Replace("chk", "")[0]) + col.UniqueName.ToLower().Replace("chk", "").Substring(1);
                    }
                    else if (col.UniqueName.ToLower().Equals("txt idusuario"))
                    {
                        col.HeaderText = char.ToUpper(col.UniqueName.ToLower().Replace("txt", "")[0]) + col.UniqueName.ToLower().Replace("txt", "").Substring(1);
                    }
                    else if (col.UniqueName.ToLower().StartsWith("dtp"))
                    {
                        col.HeaderText = char.ToUpper(col.UniqueName.ToLower().Replace("dtp", "")[0]) + col.UniqueName.ToLower().Replace("dtp", "").Substring(1);
                    }
                    else if (col.UniqueName.ToLower().Equals("id compania"))
                    {
                        col.HeaderText = char.ToUpper(col.UniqueName.ToLower().Replace("id", "")[0]) + col.UniqueName.ToLower().Replace("id", "").Substring(1);
                    }
                }
                grid.Rebind();
            }
            catch (Exception ex)
            {
                throw ex;
            }
        }
    }
}
